# fly.toml app configuration file generated for isitfiveoclock-com on 2025-04-12T01:58:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'isitfiveoclock-com'
primary_region = 'fra'

[build]

[env]
  FLASK_APP="isitfiveoclock"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
